export const ADD_BANNER_REQ = 'ADD_BANNER_REQ';
export const ADD_BANNER_SUCCESS = 'ADD_BANNER_SUCCESS';
export const ADD_BANNER_FAIL = 'ADD_BANNER_FAIL';

export const GET_BANNER_REQ = 'GET_BANNER_REQ';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_FAIL = 'GET_BANNER_FAIL';

export const DEL_BANNER_REQ = 'DEL_BANNER_REQ';
export const DEL_BANNER_SUCCESS = 'DEL_BANNER_SUCCESS';
export const DEL_BANNER_FAIL = 'DEL_BANNER_FAIL';

export const UPDATE_BANNER_REQ = 'UPDATE_BANNER_REQ';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_FAIL = 'UPDATE_BANNER_FAIL';

// export const BANNER_RESET = 'BANNER_RESET';
