export const ADD_BRAND_REQ = 'ADD_BRAND_REQ';
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';
export const ADD_BRAND_FAIL = 'ADD_BRAND_FAIL';

export const GET_BRAND_REQ = 'GET_BRAND_REQ';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAIL = 'GET_BRAND_FAIL';

export const DEL_BRAND_REQ = 'DEL_BRAND_REQ';
export const DEL_BRAND_SUCCESS = 'DEL_BRAND_SUCCESS';
export const DEL_BRAND_FAIL = 'DEL_BRAND_FAIL';

export const UPDATE_BRAND_REQ = 'UPDATE_BRAND_REQ';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const UPDATE_BRAND_FAIL = 'UPDATE_BRAND_FAIL';

// export const BRAND_RESET = 'BRAND_RESET';
