export const ADD_CATEGORY_REQ = 'ADD_CATEGORY_REQ';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAIL = 'ADD_CATEGORY_FAIL';

export const GET_CATEGORY_REQ = 'GET_CATEGORY_REQ';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const DEL_CATEGORY_REQ = 'DEL_CATEGORY_REQ';
export const DEL_CATEGORY_SUCCESS = 'DEL_CATEGORY_SUCCESS';
export const DEL_CATEGORY_FAIL = 'DEL_CATEGORY_FAIL';

export const UPDATE_CATEGORY_REQ = 'UPDATE_CATEGORY_REQ';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

// export const CATEGORY_RESET = 'CATEGORY_RESET';
