export const ADD_COUPON_REQ = 'ADD_COUPON_REQ';
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS';
export const ADD_COUPON_FAIL = 'ADD_COUPON_FAIL';

export const GET_COUPON_REQ = 'GET_COUPON_REQ';
export const GET_COUPON_SUCCESS = 'GET_COUPON_SUCCESS';
export const GET_COUPON_FAIL = 'GET_COUPON_FAIL';

export const DEL_COUPON_REQ = 'DEL_COUPON_REQ';
export const DEL_COUPON_SUCCESS = 'DEL_COUPON_SUCCESS';
export const DEL_COUPON_FAIL = 'DEL_COUPON_FAIL';

export const UPDATE_COUPON_REQ = 'UPDATE_COUPON_REQ';
export const UPDATE_COUPON_SUCCESS = 'UPDATE_COUPON_SUCCESS';
export const UPDATE_COUPON_FAIL = 'UPDATE_COUPON_FAIL';

// export const COUPON_RESET = 'COUPON_RESET';
