export const ADD_WISHLIST_REQ = 'ADD_WISHLIST_REQ';
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAIL = 'ADD_WISHLIST_FAIL';

export const GET_WISHLIST_REQ = 'GET_WISHLIST_REQ';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL';

export const DEL_WISHLIST_REQ = 'DEL_WISHLIST_REQ';
export const DEL_WISHLIST_SUCCESS = 'DEL_WISHLIST_SUCCESS';
export const DEL_WISHLIST_FAIL = 'DEL_WISHLIST_FAIL';

// export const UPDATE_WISHLIST_REQ = 'UPDATE_WISHLIST_REQ';
// export const UPDATE_WISHLIST_SUCCESS = 'UPDATE_WISHLIST_SUCCESS';
// export const UPDATE_WISHLIST_FAIL = 'UPDATE_WISHLIST_FAIL';

// export const WISHLIST_RESET = 'WISHLIST_RESET';
